Azure_Assignment/Controllers/ShopController.cs
using Azure_Assignment.DAO;
using PagedList;
using System.Net;
using System.Web.Mvc;

namespace Azure_Assignment.Controllers
{
    public class ShopController : Controller
    {
        
        ProductDAO productDAO = new ProductDAO();
        CategoryDAO categoryDAO = new CategoryDAO();
        SaleDAO saleDAO = new SaleDAO();
        SupplierDAO supplierDAO = new SupplierDAO();

        public ActionResult Index(int? id, int? page, int? brand)
        {
            TempData["CurrentCategory"] = id;
            return MainView(id, page, brand);
        }

        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            ViewBag.Categories_List = categoryDAO.Get();
            ViewBag.Suppliers_List = supplierDAO.Get();
            return PartialView();
        }

        public ActionResult ShopByBrand(int? id, int? cate, int? page)
        {
            ViewBag.Cate = null;
            if (cate != null)
            {
                ViewBag.Cate = productDAO.GetCategoryName(cate);
            }

            ViewBag.Brand = null;
            if (id != null)
            {
                ViewBag.Brand = productDAO.GetBrandName(id);
            }
            if (page == null) page = 1;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            TempData["CurrentBrand"] = id;

            if (id != null && cate != null)
            {
                var model = new ProductDAO().GetProductsByBrand_Category(id, cate).ToPagedList(pageNumber, pageSize);
                return View(model);
            }
            if (id != null)
            {
                var model = new ProductDAO().GetProductsByBrand(id).ToPagedList(pageNumber, pageSize);
                
                return View(model);
            }

            return View();
        }

        public ActionResult MainView(int? id, int? page, int? brand)
        {
            ViewBag.Cate = null;
            if (id != null)
            {
                ViewBag.Cate = productDAO.GetCategoryName(id);
            }
            
            ViewBag.Brand = null;
            if (brand != null)
            {
                ViewBag.Brand = productDAO.GetBrandName(brand);
            }
            if (page == null) page = 1;
            int pageSize = 9;
            int pageNumber = (page ?? 1);

            if (brand != null && id != null)
            {
                var model = new ProductDAO().GetProductsByCategory_Brand(id, brand).ToPagedList(pageNumber, pageSize);
                return PartialView(model);
            }

            if (id != null)
            {
                var model = new ProductDAO().GetProductsByCategory(id).ToPagedList(pageNumber, pageSize);
                return PartialView(model);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        [HttpPost]
        public ActionResult Search(string txtSearch, int? page)
        {
            if (page == null) page = 1;
            int pageSize = 9;
            int pageNumber = (page ?? 1);

            if (txtSearch != null)
            {
                var model = new ProductDAO().Search(txtSearch).ToPagedList(pageNumber, pageSize);
                return View(model);
            }

            return View();
        }
    }
}

Azure_Assignment/Controllers/UserProfileController.cs
using Azure_Assignment.EF;
using Azure_Assignment.Models;
using Azure_Assignment.Providers;
using Scrypt;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Azure_Assignment.Controllers
{
    public class UserProfileController : Controller
    {
        DataPalkia db = new DataPalkia();
        FTPServerProvider ftp = new FTPServerProvider();
        ImageProvider imgProvider = new ImageProvider();
        string ftpChild = "imgUsers";

        public ActionResult Index()
        {
            var user = (UserLogin)Session[Common.CommonConstants.CLIENT_SESSION];
            var userentity = db.Users.Find(user.Username);
            var model = new UserProfile();
            model.FirtName = userentity.FirtName;
            model.LastName = userentity.LastName;
            model.Gender = userentity.Gender;
            model.Birthday = userentity.Birthday;
            model.Phone = userentity.Phone;
            model.Email = userentity.Email;
            model.Address = userentity.Address;
            model.Picture = userentity.Picture;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Change(UserProfile profile, string imgOld_User)
        {
            if (ModelState.IsValid)
            {
                if (profile.FirtName.Trim().Length == 0 || profile.LastName.Trim().Length == 0)
                {
                    TempData["Error"] = "Name is invalid";
                    return RedirectToAction("Index");
                }

                bool isAgeValid = true;
                if ((DateTime.Now.Year - profile.Birthday.Value.Year) == 16)
                {
                    if ((DateTime.Now.Month - profile.Birthday.Value.Month) == 0)
                    {
                        if ((DateTime.Now.Day - profile.Birthday.Value.Day) > 0)
                        {
                            isAgeValid = false;
                        }
                    }
                    else if ((DateTime.Now.Month - profile.Birthday.Value.Month) > 0)
                    {
                        isAgeValid = false;
                    }
                }
                else if ((DateTime.Now.Year - profile.Birthday.Value.Year) < 16)
                {
                    isAgeValid = false;
                }

                if (!isAgeValid)
                {
                    TempData["Error"] = "Age must greater than 16 years old";
                    return RedirectToAction("Index");
                }

                var user = db.Users.Find(profile.Username);

                user.FirtName = profile.FirtName;
                user.LastName = profile.LastName;
                user.Gender = profile.Gender;
                user.Birthday = profile.Birthday;
                user.Phone = profile.Phone;
                user.Email = profile.Email;
                user.Address = profile.Address;
                user.Status = user.Status;

                string uploadFolderPath = Server.MapPath("~/public/uploadedFiles/userPictures/");
                if (profile.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(profile.ImageFile.FileName);
                    string extension = Path.GetExtension(profile.ImageFile.FileName);
                    if (imgProvider.Validate(profile.ImageFile) != null)
                    {
                        TempData["Error"] = imgProvider.Validate(profile.ImageFile);
                        return RedirectToAction("Index");
                    }
                    user.Picture = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    ftp.Update(user.Picture, ftpChild, profile.ImageFile, imgOld_User);

                }

                if (db.SaveChanges() > 0)
                {
                    TempData["SuccessMess"] = "Update successful";
                    var userSession = new Models.UserLogin();
                    userSession.Username = user.Username;
                    userSession.FirtName = user.FirtName;
                    userSession.LastName = user.LastName;
                    userSession.Gender = user.Gender;
                    userSession.Birthday = user.Birthday;
                    userSession.Phone = user.Phone;
                    userSession.Email = user.Email;
                    userSession.Address = user.Address;
                    userSession.Role = user.Role;
                    userSession.Status = user.Status;
                    userSession.Picture = ftp.Get(user.Picture, ftpChild);
                    Session.Add(Common.CommonConstants.USER_SESSION, userSession);
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(string username, string currentPass, string newPass, string confirmPass)
        {
            if (username == null || currentPass == null || newPass == null || confirmPass == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (newPass != confirmPass)
            {
                TempData["Error"] = "Confirmation password does not match!";
                return RedirectToAction("ChangePassword");
            }

            ScryptEncoder encoder = new ScryptEncoder();
            var user = db.Users.Find(username);
            bool isValidPass = encoder.Compare(currentPass, user.Password);
            if (!isValidPass)
            {
                TempData["Error"] = "Current password is incorrect!";
                return RedirectToAction("ChangePassword");
            }
            

            user.Password = encoder.Encode(newPass);
            if (db.SaveChanges() > 0)
            {
                TempData["SuccessMess"] = "Update successful";
            }
            return RedirectToAction("ChangePassword");

        }

        public ActionResult MyOrder()
        {
            if (Session[Common.CommonConstants.CLIENT_SESSION] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var user = (UserLogin)Session[Common.CommonConstants.CLIENT_SESSION];
                var model = db.Orders.Where(i => i.Username == user.Username).ToList();
                return View(model);
            }
        }

        public ActionResult OrderDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Orders orders = db.Orders.Find(id);
                var _orderDetail = (from ord in db.OrderDetails
                                    join or in db.Orders on ord.OrderID equals or.OrderID
                                    join pro in db.Products on ord.ProductID equals pro.ProductID
                                    where ord.OrderID == orders.OrderID
                                    select ord).ToList();
                ViewBag.OrderDetail = _orderDetail;
                if (orders == null)
                {
                    return HttpNotFound();
                }
                return View(orders);
            }
        }
    }
}

Azure_Assignment/Views/Shared/Breadcrumb.cshtml
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="~/home"><i class="fa fa-home"></i> Home</a>
                    <span>@ViewBag.Breadcrumb</span>
                </div>
            </div>
        </div>
    </div>
</div>

Azure_Assignment/Views/Shared/Footer.cshtml
<section class="services spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="services__item">
                    <i class="fa fa-car"></i>
                    <h6>Free Shipping</h6>
                    <p>For all oder over $99</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="services__item">
                    <i class="fa fa-money"></i>
                    <h6>Money Back Guarantee</h6>
                    <p>If good have Problems</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="services__item">
                    <i class="fa fa-support"></i>
                    <h6>Online Support 24/7</h6>
                    <p>Dedicated support</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="services__item">
                    <i class="fa fa-headphones"></i>
                    <h6>Payment Secure</h6>
                    <p>100% secure payment</p>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="instagram">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="@Url.Content("~/public/img/insta-1.jpg")">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"> palkia_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="@Url.Content("~/public/img/insta-2.jpg")">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"> palkia_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="@Url.Content("~/public/img/insta-3.jpg")">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"> palkia_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="@Url.Content("~/public/img/insta-4.jpg")">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"> palkia_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="@Url.Content("~/public/img/insta-5.jpg")">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"> palkia_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="@Url.Content("~/public/img/insta-6.jpg")">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"> palkia_shop</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="./index.html">
                            <img src="~/public/img/logo.jpg" />
                        </a>
                    </div>
                    <p>
                        Palkia Shop ensures peace of mind . Shopping - Reputation - Quality.
                    </p>
                    <div class="footer__payment">
                        <a href="#"><img src="#" alt=""></a>
                        <a href="#"><img src="#" alt=""></a>
                        <a href="#"><img src="#" alt=""></a>
                        <a href="#"><img src="#" alt=""></a>
                        <a href="#"><img src="#" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-5">
                <div class="footer__widget">
                    <h6>Quick links</h6>
                    <ul>
                        <li><a href="~/home">Home</a></li>
                        <li><a href="~/blogs">Blogs</a></li>
                        <li><a href="~/contact">Contact</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-4">
                <div class="footer__widget">
                    <h6>Account</h6>
                    <ul>
                        <li><a href="~/userprofile">My Account</a></li>
                        <li><a href="~/cart">Cart</a></li>
                        <li><a href="~/cart/checkout">Checkout</a></li>
                        <li><a href="~/userprofile/MyOrder">My Order</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-8 col-sm-8">
                <div class="footer__newslatter">
                    <h6>NEWSLETTER</h6>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        @using (Html.BeginForm("Search", "Shop", FormMethod.Post, htmlAttributes: new { @class = "search-model-form" }))
        {
             <input type="text" name="txtSearch" id="search-input" placeholder="Search here.....">
        }
    </div>
</div>

Azure_Assignment/Views/Shared/Header.cshtml
@{
    var client = (Azure_Assignment.Models.UserLogin)Session["CLIENT_SESSION"];
}
<header class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-1 col-lg-1"></div>
            <div class="col-xl-2 col-lg-1">
                <div class="header__logo">
                    <a href="~/Home">
                        <img src="~/public/img/logo.jpg" alt="" />
                    </a>
                </div>
            </div>
            <div class="col-xl-6 col-lg-7">
                @{ Html.RenderAction("Navigation", "Home"); }

            </div>
            <div class="col-lg-3">
                <div class="header__right">
                    @if (Session["CLIENT_SESSION"] == null)
                    {
                        <div class="header__right__auth">
                            <a href="~/login">Login</a>
                            <a href="~/register">Register</a>
                        </div>
                    }
                    else
                    {
                        <div class="dropdown">
                            <a onclick="largeDropdown()" class="dropbtn">Hi, @client.FirtName @client.LastName</a>
                            <div id="myDropdown" class="dropdown-content">
                                <a href="~/userprofile"><span class="icon_profile"></span>&nbsp; Profile</a>
                                <a href="~/userprofile/MyOrder"><span class="icon_cart"></span>&nbsp; My Order</a>
                                <a href="@Url.Action("ChangePassword", "UserProfile")"><span class="icon_lock"></span>&nbsp; Password</a>
                                <a href="~/logout"><span class="icon_stop_alt"></span>&nbsp; Logout</a>
                            </div>
                        </div>
                    }
                    &ensp;
                    <ul class="header__right__widget">
                        <li><span class="icon_search search-switch"></span></li>
                        <li>
                            @if (Session["CLIENT_SESSION"] != null)
                            {
                                if (client.Role == 0)
                                {
                                    <a href="~/admin">Admin</a>
                                }
                            }

                        </li>
                        <li>
                            <a href="~/cart">
                                <span class="icon_bag_alt"></span>
                                <div class="tip">@ViewBag.QuantityInCart</div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="canvas__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<style>
    .dropbtn {
        cursor: pointer;
    }

        .dropbtn:hover, .dropbtn:focus {
            background-color: #2980B9;
        }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        overflow: auto;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

    .dropdown a:hover {
        background-color: #ddd;
    }

    .show {
        display: block;
    }
</style>

<script>
    function largeDropdown() {
        document.getElementById("myDropdown").classList.toggle("show");
    }
    window.onclick = function (event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

Azure_Assignment/Views/Shared/Navigation.cshtml
<nav class="header__menu">
    <ul>
        <li class="@TempData["HomeActive"]"><a href="~/home">Home</a></li>
        @{
            foreach (var item in ViewBag.Layout_Menu)
            {
                <li class="@ViewBag.HomeActive"><a href="~/category-@item.CategoryID">@item.CategoryName</a></li>
            }
        }
        <li class="@TempData["CateActive"]">
            <a href="#">Categories</a>
            <ul class="dropdown">
                @{
                    foreach (var item in ViewBag.Categories_List)
                    {
                        <li><a href="~/category-@item.CategoryID">@item.CategoryName</a></li>
                    }
                }
            </ul>
        </li>
        <li class="@TempData["BrandActive"]">
            <a href="#">Brands</a>
            <ul class="dropdown">
                @{
                    foreach (var item in ViewBag.Suppliers_List)
                    {
                        <li><a href="~/brand-@item.SupplierID">@item.CompanyName</a></li>
                    }
                }
            </ul>
        </li>
        <li class="@TempData["BlogsActive"]"><a href="~/blogs">Blogs</a></li>
        <li class="@TempData["ContactActive"]"><a href="~/contact">Contact</a></li>
    </ul>

</nav>

Azure_Assignment/Views/Shared/_Layout.cshtml
@{
    var client = (Azure_Assignment.Models.UserLogin)Session["CLIENT_SESSION"];
}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ashion Template">
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Palkia | @ViewBag.Title</title>
    <link rel="icon" href="~/public/img/logo-in-title.png" type="image/x-icon">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

    @Styles.Render("~/bundles/core")
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/elegant-icons.css" type="text/css">

    @RenderSection("ClientStyle", false)
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>

        <ul class="offcanvas__widget">
            <li><span class="icon_search search-switch"></span></li>
            @if (Session["CLIENT_SESSION"] != null)
            {
                if (client.Role == 0)
                {
                    <li><a href="~/admin">Admin</a></li>
                }
            }
                <li>
                    <a href="~/cart">
                        <span class="icon_bag_alt"></span>
                        <div class="tip">@ViewBag.QuantityInCart</div>
                    </a>
                </li>
            </ul>
        <div class="offcanvas__logo">
            <a href="~/Home">
                <img src="~/public/img/logo.jpg" />
            </a>
        </div>
        <div id="mobile-menu-wrap"></div>

        @{
            if (Session["CLIENT_SESSION"] == null)
            {
                <div class="offcanvas__auth">
                    <a href="~/login">Login</a>
                    <a href="~/register">Register</a>
                </div>
            }
            else
            {
                <div class="dropdown">
                    <a onclick="smallDropdown()" class="dropbtn">Hi, @client.FirtName @client.LastName</a>
                    <div id="myDropdown-2" class="dropdown-content">
                        <a href="~/userprofile"><span class="icon_profile"></span>&nbsp; Profile</a>
                        <a href="~/userprofile/MyOrder"><span class="icon_cart"></span>&nbsp; My Order</a>
                        <a href="@Url.Action("ChangePassword", "UserProfile")"><span class="icon_lock"></span>&nbsp; Password</a>
                        <a href="~/logout"><span class="icon_stop_alt"></span>&nbsp; Logout</a>
                    </div>
                </div>
            }
        }
    </div>



    @{Html.RenderAction("Header", "Home");}

    @RenderBody()

    @{Html.RenderAction("Footer", "Home"); }

    <!-- jQuery -->
    <script src="~/Content/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/jquery-ui.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/jquery.countdown.min.js"></script>
    <script src="~/Content/js/jquery.slicknav.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/jquery.nicescroll.min.js"></script>
    <script src="~/Content/js/main.js"></script>

    @RenderSection("ClientScript", false)
    <script>
        function smallDropdown() {
            document.getElementById("myDropdown-2").classList.toggle("show");
        }
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>



</body>

</html>